use_frameworks!

platform :ios, '13.0'

target 'TCBKeychainManager_Example' do
  pod 'TCBKeychainManager', :path => '../'

  target 'TCBKeychainManager_Tests' do
    inherit! :search_paths

    
  end
end
